apiVersion: apps/v1
kind: Pod
metadata:
  name: readyness-example
spec:
  containers:
    - image: localhost:5000/healthcheck:latest
      name: healthcheck
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: 8080
        initialDelaySeconds: 20              # ==> Zeit bis zur ersten Prüfung
        failureThreshold: 1                 # ==> Anzahl der Fehler
        timeoutSeconds: 2                   # ==> Timeout liegt bei 1 s
        periodSeconds: 8